### ISSUE TITLE
FE - [3pt] Add and delete rooms

### ISSUE THREAD

**Issue by Andyveloper** [andgarzonmal/capstone-project-back-end#13]
# Tasks
- [ ] When the user clicks the "Add room" link in the navigation panel they get sent to a form for adding a room.
- [ ] When the user clicks the "Delete item" link in the navigation panel they can see a list of all items with titles and a "Delete" button.
- [ ] When the user clicks the "Delete" button, the selected item is marked as removed and does not show on the main list anymore.
