### ISSUE TITLE
FE - [3pt] Reservation form

### ISSUE THREAD

**Issue by Andyveloper** [andgarzonmal/capstone-project-back-end#14]
# Tasks
- [x] Build a reservations page
- [x] To reserve an appointment, the user has to select a date and city (username and selected item are auto-filled).
- [x] The user can also access the "Reserve" page from the navigation panel. In that case, only the username is auto-filled.
