### ISSUE TITLE
FE - [2pt] Navigation Panel

### ISSUE THREAD

**Issue by Andyveloper** [andgarzonmal/capstone-project-back-end#5]
# Tasks
## Navigation Panel
- [] Motorcycles/doctors/classes/items that you selected as a theme.
- [] "Reserve" form.
- [] "My reservations".
- [] "Add motorcycle/doctor/class/item that you selected as a theme" (the link is visible to everybody). - Should redirect to new item form
- [] "Delete motorcycle/doctor/class/item that you selected as a theme" (the link is visible to everybody).
