### ISSUE TITLE
FE - [2pt] Detail Page

### ISSUE THREAD

**Issue by Andyveloper** [andgarzonmal/capstone-project-back-end#8]
# Tasks
- [x] Must have all the details of the room
- [x] Must have description 
- [x] It must display the room image bigger
